/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'steven' at '6/20/17 1:30 AM' with Gradle 2.14.1
 *
 * @author steven, @date 6/20/17 1:30 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
